config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  resources :stations
  resources :properties

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :stations
  validates :property, presence: true
  validates :rent, presence: true
  validates :address, presence: true
  validates :building_age, presence: true
  validates :rent, numericality:true

  accepts_nested_attributes_for :stations, reject_if: :all_blank, :allow_destroy => true

  def check
    if minutes_walk.present? && minutes_walk1.present?
      if minutes_walk <= minutes_walk1
        errors.add(:minutes_walk, 'Station one is further than station two')
      end
    end
  end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    2.times { @property.stations.build }
  end

  # GET /properties/1/edit
  def edit
    1.times { @property.stations.build }
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property, :rent, :address, :building_age, :remarks, stations_attributes: [ :id,
                                                                                                                  :rail_way_line,
                                                                                                                  :station_name,
                                                                                                                  :minutes_walk ])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:rail_way_line, :station_name, :minutes_walk, :property_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moffom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card"><center>
      <div class="card-header"> Create New Property </div>
      <div class="card-body">

<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row mt-2">

  <div class="text-center">
  <div class="field">
    <%= f.label :property %>
    <%= f.text_field :property %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.number_field :rent %> JPY
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :building_age %>
    <%= f.number_field :building_age %>Year/Years old
  </div>

  <div class="field">
    <%= f.label :remarks %>
    <%= f.text_area :remarks %>
  </div>

  <%= f.fields_for :stations do |ff| %>
    <table>
      <hr>
      <strong><center> Name of rail way</strong><br>
      <div class="field">
        <%= ff.label :rail_way_line, "Name of rail way line" %>
        <%= ff.text_field :rail_way_line %>
      </div>

      <div class="field">
        <%= ff.label :station_name %>
        <%= ff.text_field :station_name %>
      </div>

      <div class="field">
        <%= ff.label :minutes_walk, "How many minutes walk" %>
        <%= ff.number_field :minutes_walk %>min/mins
      </div>
    </table>
  <% end %>

  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

</div>

  </div>
    </div>
      </div>
        </div>
          </div>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header"><font size="+4"> Properties</font></div>
      <div class="card-body">


<table>
  <thead>
    <table style="border:1px solid black">
      <tr>
        <th>Property | </th>
        <th>Rent | </th>
        <th>Address | </th>
        <th>Building age | </th>
        <th>Remarks </th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.building_age %></td>
        <td><%= property.remarks %></td>
        <td><%= link_to 'Show', property , class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_property_path(property) , class: "btn btn-primary"  %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn "%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="actions">
  <%= link_to 'New Property', new_property_path , class: "btn btn-primary"  %>
</div>

  </div>
    </div>
      </div>
        </div>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property.property %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Building age:</strong>
  <%= @property.building_age %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @property.remarks %>
</p>
<hr>
<% @property.stations.each do |poor| %>
  <h2><b>Nearest station </b></h2>
  <p>
    <strong>Name of railway line:</strong>
    <%= poor.rail_way_line %>
  </p>

  <p>
    <strong>Station name:</strong>
    <%= poor.station_name %>
  </p>

  <p>
    <strong>How many minutes walks:</strong>
    <%= poor.minutes_walk %>
    </p>
<% end %>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rail_way_line %>
    <%= f.text_field :rail_way_line %>
  </div>

  <div class="field">
    <%= f.label :station_name %>
    <%= f.text_field :station_name %>
  </div>

  <div class="field">
    <%= f.label :minutes_walk %>
    <%= f.number_field :minutes_walk %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Rail way line</th>
      <th>Station name</th>
      <th>Minutes walk</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.rail_way_line %></td>
        <td><%= station.station_name %></td>
        <td><%= station.minutes_walk %></td>
        <td><%= station.property %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rail way line:</strong>
  <%= @station.rail_way_line %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @station.station_name %>
</p>

<p>
  <strong>Minutes walk:</strong>
  <%= @station.minutes_walk %>
</p>

<p>
  <strong>Property:</strong>
  <%= @station.property %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>